### ISSUE TITLE
CI only running 19 tests

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#298]
My local suite runs 54 tests. Is something still guarded on the CI?

https://travis-ci.com/rlworkgroup/garage/builds/82191539
https://travis-ci.com/rlworkgroup/garage/builds/82168745

**Comment by jonashen** [comment]
Some CIs are running 19, others 54. Not sure yet what the source of the deviation is.

**Comment by jonashen** [comment]
I'm fairly certain it's because of this: `ImportError: cannot import name 'MemmapingPool'`.

This is probably why some tests aren't running, e.g. `AttributeError: module 'tests.theano.algos' has no attribute 'test_algos'`.

**Comment by ryanjulian** [comment]
That only occurs when you upgrade joblib to >0.10, but the environment.yml on master is using joblib 0.10 and we have not committed Angel's change to upgrade.

Where did you see these errors?

**Comment by ryanjulian** [comment]
`master` is still using joblib 0.10.3, but its builds are still only running 19 tests (see https://travis-ci.com/rlworkgroup/garage/builds/82260970)

It appears that the regression was introduced by #270 
`master` build before #270 https://travis-ci.com/rlworkgroup/garage/builds/81870318
`master` build after #270 https://travis-ci.com/rlworkgroup/garage/builds/81941351

Since you introduced the regression which wiped out >50% of our test suite, can you please fix it ASAP?

**Comment by ryanjulian** [comment]
I suspect this might be because nose2 doesn't recognize test packages withoout `__init__.py` files, despite the fact that Python 3 was released a decade ago.

**Comment by ryanjulian** [comment]
Reopened until comments on #311 are addressed in a new commit
